// the-slider-test/libraries/react/src/App.js
import React, { useState } from 'react';

import Input from './Input';
import Slider from './Slider';

import './App.css';

export default () => {
	let [current_value, setValue] = useState(50);
	let min = 0;
	let max = 100;

	return (
		<div className='demo'>
			<Slider value={current_value} min={min} max={max} onChange={setValue} />	
			<Input value={current_value} min={min} max={max} onChange={setValue} />
		</div>
	);
};

// the-slider-test/libraries/svelte/src/App.svelte
<script>
	// Components
	import Slider from './Slider.svelte';
	import Input from './Input.svelte';

	// Props
	export let min = 0;
	export let max = 100;
	export let value = 50;

</script>

<style>
	:global(.demo) {
		display: flex;
		width: 100%;
	}

	:global(.demo .uix-slider) {
		flex-grow: 1;
	}
</style>

<div class='demo'>
	<Slider bind:min={min} bind:max={max} bind:value={value}/>
	<Input bind:min={min} bind:max={max} bind:value={value} />
</div>
